integration with docker
puikinsh/Adminator-admin-dashboard pull request #110
Opened 2018-08-13 10:14 UTC by aagarwal2286

this pull request is to make this awesome repository docker compatible so that users may start working without running into environment setup issues.

2018-09-01 09:54 UTC, krzysiekpiasecki commented
@aagarwal2286  There is an ERROR when `docker-compose up --build` after cloning your branch.

> ui    | npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
> ui    | npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
> ui    | npm ERR! request to https://registry.npmjs.org/babel-polyfill failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net
> ui    | 
> ui    | npm ERR! A complete log of this run can be found in:
> ui    | npm ERR!     /root/.npm/_logs/2018-09-01T09_51_37_221Z-debug.log
> ui    | 
> ui    | > adminator@1.0.0 docker-dev /home/node/app
> ui    | > webpack-dev-server
> ui    | 
> ui    | sh: 1: webpack-dev-server: not found
> ui    | npm ERR! file sh
> ui    | npm ERR! code ELIFECYCLE
> ui    | npm ERR! errno ENOENT
> ui    | npm ERR! syscall spawn
> ui    | npm ERR! adminator@1.0.0 docker-dev: `webpack-dev-server`
> ui    | npm ERR! spawn ENOENT
> ui    | npm ERR! 
> ui    | npm ERR! Failed at the adminator@1.0.0 docker-dev script.
> ui    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> ui    | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> ui    | 
> ui    | npm ERR! A complete log of this run can be found in:
> ui    | npm ERR!     /root/.npm/_logs/2018-09-01T09_51_37_536Z-debug.log


You should also change the name of the container.

2018-09-01 09:56 UTC, krzysiekpiasecki requested changes
Container name is to general and error occurs when running this container.

2018-09-06 04:01 UTC, aagarwal2286 commented
> ui | npm ERR! request to https://registry.npmjs.org/babel-polyfill failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net

Seems it's temporary issue from npm side and resolved now. I have checked it in my local and it's working as expected.
Please refer discussion -> https://npm.community/t/registry-npmjs-org-certification-invalid/1860/5

2019-05-02 11:05 UTC, krzysiekpiasecki commented
@aagarwal2286  You were right. It works.

2019-05-02 11:09 UTC, krzysiekpiasecki commented on package.json
> +    "docker-dev": "webpack-dev-server",
Duplicate of start script

2019-05-03 09:05 UTC, krzysiekpiasecki requested changes
Successfully tested on Mac OS environment. After merge it could be added to docker hub.

2019-05-03 09:05 UTC, krzysiekpiasecki commented on README.md
> +```
Add minimum compatibility version for docker binary

2019-05-03 09:05 UTC, krzysiekpiasecki commented on init.sh
> +#!/bin/bash
The script name is to general IMHO. This script modifies global git settings and can be executed out of the docker context. It's reasonable to name it e.g. docker-init.sh. I'm not to much familiar with the docker. Is it possible to inline this three commands into a configuration file?

2019-05-03 09:05 UTC, krzysiekpiasecki commented on docker-compose.yaml
> +    container_name: ui
s/ui/adminator/g

2019-05-03 09:05 UTC, krzysiekpiasecki commented on package.json
> +    "docker-dev": "webpack-dev-server",
Duplicate of start script

2019-05-03 10:30 UTC, krzysiekpiasecki requested changes

2019-05-03 10:30 UTC, krzysiekpiasecki commented on README.md
> +```
Files/Folders Structure needs update too.

2022-08-28 12:39 UTC, jepperaskdk commented
Thanks for contributing this. I'm wondering if it is necessary though, as our only dependency is node-12.
You could just run the node-12 image directly, mounting your current directory (adminator) into /app:
`docker run -v $(pwd):/app -p 3000:3000 -it node:12-buster-slim /bin/bash`
Scripts for cloning the repository (init.sh) I wouldn't add in the repository.

Should we close as stale?

2022-09-01 19:18 UTC, jepperaskdk commented
Closing, let me know if you think it should be reopened.

2022-09-01 19:18 UTC, closed without merging